export default {
    DEFAULT_BUTTON_ANCHOR: {
        x: 0.5,
        y: 0.5,
    },
    DEFAULT_TEXT_ANCHOR: {
        x: 0.5,
        y: 0,
    },
    DEFAULT_TEXT_FONT: 'Georgia',
    DEFAULT_FONT_SIZE: 20,
    DEFAULT_TEXT_COLOR: 'white',
    DEFAULT_TEXT_OUTLINE_COLOR: 'black',
    DEFAULT_TEXT_ALIGNMENT: 'center',
    DEFAULT_TEXTBUTTON_FONT: 'Georgia',
    DEFAULT_TEXTBUTTON_COLOR: '#555555',
    DEFAULT_TEXTBUTTON_TEXT_COLOR: '#FFFFFF',
    DEFAULT_BUTTON_PADDING_SCALE: 0.2,
    DEFAULT_BUTTON_RADIUS: 10,
};
